### ISSUE TITLE
Temperature not updating

### ISSUE THREAD

**Issue by fafoulon** [codyc1515/homebridge-ismartgate#1]
Hi,
Thanks for the awesome plugin.
I have a small issue, after two or three days of homebridge being up, the temperature is always displaying 0.0°C.
If I restart the service, the right temperature appears again... for some days.

**Comment by codyc1515** [comment]
Probably the IP address of the iSmartGate device is changing. I find it reconnects quite often. There is currently nothing to detect this, but I will take a look & see what I can do.

**Comment by nielsvaneck** [comment]
I was having this same issue. I looked at my logs and found that the plugin can’t find the ismartgate device. 

I turned on debug logging and tried hardcoding the IP address (but that’s really not a good permanent solution)

After that, I noticed that the plugin still is not able to login properly. 

I opened the login page with the browser and noticed that the iSmartGate is throwing up a Captcha on the login page : (

Ended up setting up a "wifi-only" user in the iSmartgate app for Homebridge access and re-installing the plugin with that user & hardcoded IP.   It works for now..

**Comment by fafoulon** [comment]
Smart solution 😀 Thanks for that troubleshooting!

**Comment by codyc1515** [comment]
Are you still experiencing issues? I pushed a stability update recently which should reduce occurrences of this.

**Comment by stormshaker** [comment]
I was also receiving 0 for temperature and battery for the last few days. Just updated to your new release, and that’s fixed it. Well done 👍
