### ISSUE TITLE
Plugin thinks my Unifi controller is an iSmartGate because of mDNS

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [codyc1515/homebridge-ismartgate#10]
Using the oznu/homebridge Docker container to manage Homebridge. The error message this plugin gives me is `Could not login. null <ref *2> IncomingMessage`.

Seems like this plugin is trying to log into my Unifi controller: 
`[iSmartGate Temperature] Found an iSmartGate at 192.168.4.1`

That's my Unifi controller's IP address.

Going down some lines in the log I see the attempt on my Unifi controller:
```
 _header: 'POST /index.php HTTP/1.1\r\n' +
        'host: 192.168.4.1\r\n' +
        'content-type: application/x-www-form-urlencoded\r\n' +
        'content-length: 44\r\n' +
        'Connection: close\r\n' +
        '\r\n',
```

My SmartGate is actually at 192.168.2.41.
config.json:

```
    "accessories": [
        {
            "name": "iSmartGate Temperature",
            "hostname": "192.168.2.41",
            "username": "admin",
            "password": "redacted",
            "accessory": "iSmartGate"
        }
    ],
```

In the code, I see this snippet that tells it to use mDNS to find the iSmartGate:
https://github.com/codyc1515/homebridge-ismartgate/blob/501a0981a0876d512ae99783c9bf9671fd76679f/index.js#L55-L74

Is there any way I can just tell it to use a specific IP address instead of relying on mDNS? My Homebridge container and iSmartGate are on different VLANs so I suspect that's causing the problem here, but I don't want to compromise IoT security by moving them onto the same VLAN.

**Comment by codyc1515** [comment]
We previously used the direct IP address but this could oftentimes change unless you set static IPs. In any case, there is a native integration in Home Assistant which you should check out.
