### ISSUE TITLE
iSmartgate does not work anymore?

### ISSUE THREAD

**Issue by casperse** [codyc1515/homebridge-ismartgate#12]
Hi

Really love this plugin to Home bridge!
But I think the latest updates to Homebridge have broken it?

![image](https://user-images.githubusercontent.com/2026859/163635230-bdc48167-ff24-474a-9911-7a0bdc878043.png)

Seems that it cant connect to the server anymore?

**Comment by codyc1515** [comment]
Are you still having this issue? If so, Home Assistant has a native integration for iSmartGate that you should check-out.
