### ISSUE TITLE
Shows 0C and 0%

### ISSUE THREAD

**Issue by mstendah** [codyc1515/homebridge-ismartgate#13]
Hi, the plugin shows only zero values on teh accessories. There are no error messages in the logs. Just one line showing that it successfully found and connected to my iSmartGate Pro.

**Comment by codyc1515** [comment]
Sorry, I don’t have any iSmartGate Pro to test with. It may well be the case that the data available is different than regular iSmartGate. I would suggest to try Home Assistant in that case.
