### ISSUE TITLE
config.motion

### ISSUE THREAD

**Issue by iNullNet** [codyc1515/homebridge-ismartgate#5]
sorry but what need to wrote in config.json of homebridge? i’ve tried to copy config.schema.json but seems doesn’t works. Maybe i’ve wrote in bad place? I’ve put in platform...

**Comment by codyc1515** [comment]
Hi there

There is support for config-ui-x plug-in now. Let me know if you're still having issues.

Cody

**Comment by iNullNet** [comment]
yeah! now it's works! thank you so much
