### ISSUE TITLE
Add Camera?

### ISSUE THREAD

**Issue by stormshaker** [codyc1515/homebridge-ismartgate#6]
I've been looking at how to get the iSmartGate camera exposed through Homekit, and I think as part of this plugin would be ideal as you're already doing the login. What are your thoughts?

This is the URL that contains the snapshots from the camera, refreshing every second with the current epoc time as a parameter:
`<img src="./camController.php?t=1601204921" class="img-home img-close" name="refresh" id="refresh">`

**Comment by codyc1515** [comment]
Hi there - sorry I didn't see this till now.

It is likely quite a bit of work to add this with streaming... however, it can be straightforward to just add the snapshots.

Can you please provide a wider excerpt from the page source?

Kind regards
Cody

**Comment by gjs12** [comment]
You can expose the camera through the camera ffmpeg plugin, the rtsp url is rtsp://usern:pwd@IP:554/videoMain. You need to turn on onvif authentication on the camera which can be done through the foscam VMS app, at least that was what I had to do.

**Comment by codyc1515** [comment]
Is this working for you now gjs12?

**Comment by codyc1515** [comment]
Close due no response.
